- name: Deploy BookMyShow to EKS
  hosts: localhost
  tasks:

    - name: Apply Deployment
      kubernetes.core.k8s:
        state: present
        namespace: default
        src: deployment.yml
        template:
          IMAGE_TAG: "{{ lookup('env','IMAGE_TAG') }}"

    - name: Apply Service
      kubernetes.core.k8s:
        state: present
        namespace: default
        src: service.yml
