---
- name: Deploy BookMyShow to EKS
  hosts: localhost
  tasks:

    - name: Apply Deployment
      kubernetes.core.k8s:
        state: present
        src: deployment.yml
        namespace: default

    - name: Apply Service
      kubernetes.core.k8s:
        state: present
        src: service.yml
        namespace: default
